name: Metrics

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Neolemoz
          template: classic
          base: header, activity
          config_timezone: Asia/Bangkok
